// <auto-generated />
using System;
using AdapostAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdapostAPI.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220113033012_VizitatorAndAdapostTable")]
    partial class VizitatorAndAdapostTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdapostAPI.DAL.Entities.Adapost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("Adaposts");
                });

            modelBuilder.Entity("AdapostAPI.DAL.Entities.AdapostVizitator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdapostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVizitei")
                        .HasColumnType("datetime2");

                    b.Property<int>("VizitatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdapostId");

                    b.HasIndex("VizitatorId");

                    b.ToTable("AdapostVizitator");
                });

            modelBuilder.Entity("AdapostAPI.DAL.Entities.Adoptanti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Adoptantis");
                });

            modelBuilder.Entity("AdapostAPI.DAL.Entities.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdapostId")
                        .HasColumnType("int");

                    b.Property<int?>("AdoptantiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInmatriculare")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Greutate")
                        .HasMaxLength(30)
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("Inaltime")
                        .HasMaxLength(30)
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Specie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("varsta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdapostId");

                    b.HasIndex("AdoptantiId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("AdapostAPI.DAL.Entities.Employeer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdapostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAngajarii")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Salariu")
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("Id");

                    b.HasIndex("AdapostId");

                    b.ToTable("Employeers");
                });

            modelBuilder.Entity("AdapostAPI.DAL.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Judet")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Numar")
                        .HasColumnType("int");

                    b.Property<string>("Oras")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Strada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("AdapostAPI.DAL.Entities.Vizitator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vizitator");
                });

            modelBuilder.Entity("AdapostAPI.DAL.Entities.Adapost", b =>
                {
                    b.HasOne("AdapostAPI.DAL.Entities.Location", "Location")
                        .WithOne("Adapost")
                        .HasForeignKey("AdapostAPI.DAL.Entities.Adapost", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AdapostAPI.DAL.Entities.AdapostVizitator", b =>
                {
                    b.HasOne("AdapostAPI.DAL.Entities.Adapost", "Adapost")
                        .WithMany("AdapostVizitators")
                        .HasForeignKey("AdapostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdapostAPI.DAL.Entities.Vizitator", "Vizitator")
                        .WithMany("AdapostVizitators")
                        .HasForeignKey("VizitatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adapost");

                    b.Navigation("Vizitator");
                });

            modelBuilder.Entity("AdapostAPI.DAL.Entities.Animal", b =>
                {
                    b.HasOne("AdapostAPI.DAL.Entities.Adapost", "Adapost")
                        .WithMany("Animals")
                        .HasForeignKey("AdapostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdapostAPI.DAL.Entities.Adoptanti", "Adoptanti")
                        .WithMany("Animal")
                        .HasForeignKey("AdoptantiId");

                    b.Navigation("Adapost");

                    b.Navigation("Adoptanti");
                });

            modelBuilder.Entity("AdapostAPI.DAL.Entities.Employeer", b =>
                {
                    b.HasOne("AdapostAPI.DAL.Entities.Adapost", "Adapost")
                        .WithMany("Employeers")
                        .HasForeignKey("AdapostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adapost");
                });

            modelBuilder.Entity("AdapostAPI.DAL.Entities.Adapost", b =>
                {
                    b.Navigation("AdapostVizitators");

                    b.Navigation("Animals");

                    b.Navigation("Employeers");
                });

            modelBuilder.Entity("AdapostAPI.DAL.Entities.Adoptanti", b =>
                {
                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AdapostAPI.DAL.Entities.Location", b =>
                {
                    b.Navigation("Adapost");
                });

            modelBuilder.Entity("AdapostAPI.DAL.Entities.Vizitator", b =>
                {
                    b.Navigation("AdapostVizitators");
                });
#pragma warning restore 612, 618
        }
    }
}
